### PR TITLE
update chart version to v0.2.0

### PR DESCRIPTION
**Pull request by michelleN**
I should have updated this before cutting the release on both main and the tag

### CODE REVIEW

**Comment by endocrimes** [comment]
@vdice I understand the comment above the version number to mean we never need to bump it in the files? - but it just happens for releases in the machinery?

**Comment by endocrimes** [comment]
https://github.com/spinkube/spin-operator/blob/main/scripts/update-chart-versions.sh#L12-L14 - yeah it eventually gets overwritten by this - I don't think we want to add updating these to the release process tbh 😅

**Comment by michelleN** [comment]
The versions did not get updated by release machinery on the last release. What version do you think they should point to? Wouldn't want them to point to v0.1.0 forever since that is outdated. We don't use the latest tag. Pointing to the latest release makes sense to me. Do you have another option in mind? @endocrimes

**Comment by michelleN** [comment]
Adding more context: The versions did get updated in the release artifacts properly but not the main branch. If you checkout the v0.2.0, the chart version is v0.1.0 there as well.

**Comment by endocrimes** [comment]
We don't really support helm for development, so I'm not sure folks installing the chart from source is a big risk?

**Comment by endocrimes** [comment]
I mostly feel a little bit weird about adding manual steps to things for unsupported installation mechanisms (esp when for everything else we derive versioning from `git`) - but also wouldn't really want to have to maintain a bunch of automation to open PRs for this automatically 😅

**Comment by michelleN** [comment]
> I mostly feel a little bit weird about adding manual steps to things for unsupported installation mechanisms (esp when for everything else we derive versioning from git) - but also wouldn't really want to have to maintain a bunch of automation to open PRs for this automatically 😅

This chart is our repo so we do need to keep it up to date or move it from the repo.
One way to proceed:
1) merge this PR so main is at least not out of date
2) propose a new repo in spinkube to house the spinkube charts and add some automation there that bumps versions when there is a new release of spin-operator

Another option:
1) merge this PR
2) create automation as you mentioned above to open PRs automatically after a release

Does anyone else have other ideas?

**Comment by calebschoepp** [comment]
@michelleN is the community precedent to have helm charts in their own repo or together with what they're packaging? I would want to follow the precedent.

Would it make sense to have bumping the chart version be part of the release process? Instead of submitting PRs after a release?

Either way I agree that we should merge this PR to make main less out of date.

**Comment by calebschoepp** [comment]
Superseded by https://github.com/spinkube/spin-operator/pull/311

**Pull request closed without merging**
